using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Script.Services;
using System.Web.Services;

namespace ContactListService
{
    /// <summary>
    /// Summary description for Service1
    /// </summary>
    [WebService(Namespace = "http://tempuri.org/")]
    [WebServiceBinding(ConformsTo = WsiProfiles.BasicProfile1_1)]
    [System.ComponentModel.ToolboxItem(false)]
    // To allow this Web Service to be called from script, using ASP.NET AJAX, uncomment the following line. 
    [System.Web.Script.Services.ScriptService]
    public class ContactList : System.Web.Services.WebService
    {
        private List<Contact> contacts = new List<Contact>()
                                             {
                                                 new Contact() {firstName = "Tommy", lastName = "Maintz"},
                                                 new Contact() {firstName = "Ed", lastName = "Spencer"},
                                                 new Contact() {firstName = "Jamie", lastName = "Avins"},
                                                 new Contact() {firstName = "Aaron 2nd", lastName = "Conran"},
                                                 new Contact() {firstName = "Dave", lastName = "Kaneda"},
                                                 new Contact() {firstName = "Michael", lastName = "Mullany"},
                                                 new Contact() {firstName = "Abraham", lastName = "Elias"},
                                                 new Contact() {firstName = "Jeremmy", lastName = "Robinson"},
                                                 new Contact() {firstName = "Sunny", lastName = "Maintz"},
                                                 new Contact() {firstName = "Edie", lastName = "Spencer"},
                                                 new Contact() {firstName = "Michael", lastName = "Mullany"},
                                                 new Contact() {firstName = "Abraham", lastName = "Elias"},
                                                 new Contact() {firstName = "Jay", lastName = "Robinson"},
                                                 new Contact() {firstName = "Mike", lastName = "Maintz"},
                                                 new Contact() {firstName = "Leon", lastName = "Spencer"},
                                                 new Contact() {firstName = "Jamie", lastName = "Avins"},
                                                 new Contact() {firstName = "Stan", lastName = "Conran"},
                                                 new Contact() {firstName = "Dave", lastName = "Kaneda"},
                                                 new Contact() {firstName = "Michael", lastName = "Mullany"},
                                                 new Contact() {firstName = "Abraham", lastName = "Elias"},
                                                 new Contact() {firstName = "Jay", lastName = "Robinson"},
                                                 new Contact() {firstName = "Roy", lastName = "Jackson"},
                                                 new Contact() {firstName = "May", lastName = "Stoned"},
                                                 new Contact() {firstName = "Michael", lastName = "Gutenberg"},
                                                 new Contact() {firstName = "Pavlo", lastName = "Pidlypenskyi"},
                                                 new Contact() {firstName = "Mike", lastName = "McStanely"},
                                                 new Contact() {firstName = "Paul", lastName = "Podlipensky"},
                                                 new Contact() {firstName = "Big", lastName = "Bear"},
                                                 new Contact() {firstName = "Roy", lastName = "Menson"},
                                                 new Contact() {firstName = "Nikolya", lastName = "Paris"},
                                                 new Contact() {firstName = "Joe", lastName = "Skinder"},
                                                 new Contact() {firstName = "Jay", lastName = "Robinson"},
                                                 new Contact() {firstName = "Zed", lastName = "Zacharias"},
                                                 new Contact() {firstName = "Abbott", lastName = "Father"},
                                                 new Contact() {firstName = "Abel", lastName = "Eagle"},
                                                 new Contact() {firstName = "Abner", lastName = "Dark"},
                                                 new Contact() {firstName = "Abraham", lastName = "Zacharias"},
                                                 new Contact() {firstName = "Adam", lastName = "Zacharias"},
                                                 new Contact() {firstName = "Addison", lastName = "Zacharias"},
                                                 new Contact() {firstName = "Adler", lastName = "White"},
                                                 new Contact() {firstName = "Adley", lastName = "Zacharias"},
                                                 new Contact() {firstName = "Adrian", lastName = "Zacharias"},
                                                 new Contact() {firstName = "Alan", lastName = "Supernaturally"},
                                                 new Contact() {firstName = "Albert", lastName = "Zacharias"},
                                                 new Contact() {firstName = "Alexander", lastName = "Zacharias"},
                                                 new Contact() {firstName = "Brian", lastName = "White"},
                                                 new Contact() {firstName = "Brian", lastName = "Zacharias"},
                                                 new Contact() {firstName = "Caldwell", lastName = "Pledge"},
                                                 new Contact() {firstName = "Calvin", lastName = "Zacharias"},
                                                 new Contact() {firstName = "Carrick", lastName = "Pledge"},
                                                 new Contact() {firstName = "Thomas", lastName = "Luddington"},
                                                 new Contact() {firstName = "Master", lastName = "Maruyn"},
                                                 new Contact() {firstName = "Master", lastName = "Gardyner"},
                                                 new Contact() {firstName = "Captain", lastName = "Vaughan"},
                                                 new Contact() {firstName = "Master", lastName = "Kendall"},
                                                 new Contact() {firstName = "Master", lastName = "Prideox"},
                                                 new Contact() {firstName = "Robert", lastName = "Holecroft"},
                                                 new Contact() {firstName = "Rise", lastName = "Courtenay"},
                                                 new Contact() {firstName = "Thomas", lastName = "Foxe"},
                                                 new Contact() {firstName = "Edward", lastName = "Nugen"},
                                                 new Contact() {firstName = "Darby", lastName = "Glande"},
                                                 new Contact() {firstName = "Edward", lastName = "Kelle"},
                                                 new Contact() {firstName = "Iohn", lastName = "Gostigo"},
                                                 new Contact() {firstName = "Erasmus", lastName = "Clefs"},
                                                 new Contact() {firstName = "Edward", lastName = "Ketcheman"},
                                                 new Contact() {firstName = "Iohn", lastName = "Linsey"},
                                                 new Contact() {firstName = "Thomas", lastName = "Rottenbury"},
                                                 new Contact() {firstName = "Roger", lastName = "Deane"},
                                                 new Contact() {firstName = "Iohn", lastName = "Harris"},
                                                 new Contact() {firstName = "Frauncis", lastName = "Norris"},
                                                 new Contact() {firstName = "Mathewe", lastName = "Lyne"},
                                                 new Contact() {firstName = "Edward", lastName = "Kettell"},
                                                 new Contact() {firstName = "Thomas", lastName = "Wisse"},
                                                 new Contact() {firstName = "Robert", lastName = "Biscombe"},
                                                 new Contact() {firstName = "William", lastName = "Backhouse"},
                                                 new Contact() {firstName = "William", lastName = "White"},
                                                 new Contact() {firstName = "Henry", lastName = "Potkin"},
                                                 new Contact() {firstName = "Dennis", lastName = "Barnes"},
                                                 new Contact() {firstName = "Ioseph", lastName = "Borges"},
                                                 new Contact() {firstName = "William", lastName = "Tenche"},
                                                 new Contact() {firstName = "Randall", lastName = "Latham"},
                                                 new Contact() {firstName = "Thomas", lastName = "Hulme"},
                                                 new Contact() {firstName = "Walter", lastName = "Myll"},
                                                 new Contact() {firstName = "Richard", lastName = "Gilbert"},
                                                 new Contact() {firstName = "Steuen", lastName = "Pomarie"},
                                                 new Contact() {firstName = "Iohn", lastName = "Brocke"},
                                                 new Contact() {firstName = "Bennet", lastName = "Harrye"},
                                                 new Contact() {firstName = "Iames", lastName = "Stevenson"},
                                                 new Contact() {firstName = "Charles", lastName = "Stevenson"},
                                                 new Contact() {firstName = "Christopher", lastName = "Lowde"},
                                                 new Contact() {firstName = "Ieremie", lastName = "Man"},
                                                 new Contact() {firstName = "Iames", lastName = "Mason"},
                                                 new Contact() {firstName = "Dauvid", lastName = "Salter"},
                                                 new Contact() {firstName = "Richard", lastName = "Ireland"},
                                                 new Contact() {firstName = "Thomas", lastName = "Bookener"},
                                                 new Contact() {firstName = "William", lastName = "Philippes"},
                                                 new Contact() {firstName = "Randall", lastName = "Mayne"},
                                                 new Contact() {firstName = "Master", lastName = "Snelling"},
                                                 new Contact() {firstName = "Master", lastName = "Allyne"},
                                                 new Contact() {firstName = "Iohn", lastName = "Cage"},
                                                 new Contact() {firstName = "Thomas", lastName = "Parre"},
                                                 new Contact() {firstName = "William", lastName = "Randes"},
                                                 new Contact() {firstName = "Geffery", lastName = "Churchman"},
                                                 new Contact() {firstName = "William", lastName = "Farthowe"},
                                                 new Contact() {firstName = "Iohn", lastName = "Taylor"},
                                                 new Contact() {firstName = "Philppe", lastName = "Robyns"},
                                                 new Contact() {firstName = "Thomas", lastName = "Phillippes"},
                                                 new Contact() {firstName = "Valentine", lastName = "Beale"},
                                                 new Contact() {firstName = "Iames", lastName = "Skinner"},
                                                 new Contact() {firstName = "George", lastName = "Eseuen"},
                                                 new Contact() {firstName = "John", lastName = "Chaundeler"},
                                                 new Contact() {firstName = "Philip", lastName = "Blunt"},
                                                 new Contact() {firstName = "Richard", lastName = "Poore"},
                                                 new Contact() {firstName = "Robert", lastName = "Yong"},
                                                 new Contact() {firstName = "Marmaduke", lastName = "Constable"},
                                                 new Contact() {firstName = "Thomas", lastName = "Hesket"},
                                                 new Contact() {firstName = "William", lastName = "Wasse"},
                                                 new Contact() {firstName = "Iohn", lastName = "Feuer"},
                                                 new Contact() {firstName = "Thomas", lastName = "Taylor"},
                                                 new Contact() {firstName = "Richard", lastName = "Humfrey"},
                                                 new Contact() {firstName = "Iohn", lastName = "Wright"},
                                                 new Contact() {firstName = "Gabriell", lastName = "North"},
                                                 new Contact() {firstName = "Bennet", lastName = "Chappell"},
                                                 new Contact() {firstName = "Richard", lastName = "Sare"},
                                                 new Contact() {firstName = "Iames", lastName = "Lasie"},
                                                 new Contact() {firstName = "Thomas", lastName = "Smart"},
                                                 new Contact() {firstName = "Iohn", lastName = "Evans"},
                                                 new Contact() {firstName = "Roger", lastName = "Large"},
                                                 new Contact() {firstName = "Humfrey", lastName = "Garden"},
                                                 new Contact() {firstName = "Frauncis", lastName = "Whitton"},
                                                 new Contact() {firstName = "Rowland", lastName = "Griffyn"},
                                                 new Contact() {firstName = "William", lastName = "Millard"},
                                                 new Contact() {firstName = "Edwarde", lastName = "Seklemore"},
                                                 new Contact() {firstName = "Iohn", lastName = "Anwike"},
                                                 new Contact() {firstName = "Christopher", lastName = "Marshall"},
                                                 new Contact() {firstName = "Dauid", lastName = "Williams"},
                                                 new Contact() {firstName = "Nicholas", lastName = "Swabber"},
                                                 new Contact() {firstName = "Edward", lastName = "Chipping"},
                                                 new Contact() {firstName = "Syluester", lastName = "Beching"},
                                                 new Contact() {firstName = "Vincent", lastName = "Cheyne"},
                                                 new Contact() {firstName = "Haunce", lastName = "Walters"},
                                                 new Contact() {firstName = "Edward", lastName = "Barecombe"},
                                                 new Contact() {firstName = "Thomas", lastName = "Skeuelabs"},
                                                 new Contact() {firstName = "Thomas", lastName = "Warner"},
                                                 new Contact() {firstName = "Anthony", lastName = "Cage"},
                                                 new Contact() {firstName = "John", lastName = "Jones"},
                                                 new Contact() {firstName = "John", lastName = "Tydway"},
                                                 new Contact() {firstName = "Ambrose", lastName = "Viccars"},
                                                 new Contact() {firstName = "Edmond", lastName = "English"},
                                                 new Contact() {firstName = "Thomas", lastName = "Topan"},
                                                 new Contact() {firstName = "Henry", lastName = "Berrye"},
                                                 new Contact() {firstName = "Richard", lastName = "Berrye"},
                                                 new Contact() {firstName = "John", lastName = "Spendlove"},
                                                 new Contact() {firstName = "John", lastName = "Hemmington"},
                                                 new Contact() {firstName = "Thomas", lastName = "Butler"},
                                                 new Contact() {firstName = "Edward", lastName = "Powell"},
                                                 new Contact() {firstName = "John", lastName = "Burden"},
                                                 new Contact() {firstName = "James", lastName = "Hynde"},
                                                 new Contact() {firstName = "Thomas", lastName = "Ellis"},
                                                 new Contact() {firstName = "William", lastName = "Browne"},
                                                 new Contact() {firstName = "Michael", lastName = "Myllet"},
                                                 new Contact() {firstName = "Thomas", lastName = "Smith"},
                                                 new Contact() {firstName = "Richard", lastName = "Kemme"},
                                                 new Contact() {firstName = "Thomas", lastName = "Harris"},
                                                 new Contact() {firstName = "Richard", lastName = "Taverner"},
                                                 new Contact() {firstName = "John", lastName = "Earnest"},
                                                 new Contact() {firstName = "Henry", lastName = "Johnson"},
                                                 new Contact() {firstName = "John", lastName = "Starte"},
                                                 new Contact() {firstName = "Richard", lastName = "Darige"},
                                                 new Contact() {firstName = "William", lastName = "Lucas"},
                                                 new Contact() {firstName = "Arnold", lastName = "Archard"},
                                                 new Contact() {firstName = "John", lastName = "Wright"},
                                                 new Contact() {firstName = "William", lastName = "Dutton"},
                                                 new Contact() {firstName = "Morris", lastName = "Allen"},
                                                 new Contact() {firstName = "William", lastName = "Waters"},
                                                 new Contact() {firstName = "Richard", lastName = "Arthur"},
                                                 new Contact() {firstName = "John", lastName = "Chapman"},
                                                 new Contact() {firstName = "William", lastName = "Clement"},
                                                 new Contact() {firstName = "Robert", lastName = "Little"},
                                                 new Contact() {firstName = "Hugh", lastName = "Tayler"},
                                                 new Contact() {firstName = "Richard", lastName = "Wildye"},
                                                 new Contact() {firstName = "Lewes", lastName = "Wotton"},
                                                 new Contact() {firstName = "Michael", lastName = "Bishop"},
                                                 new Contact() {firstName = "Henry", lastName = "Browne"},
                                                 new Contact() {firstName = "Henry", lastName = "Rufoote"},
                                                 new Contact() {firstName = "Richard", lastName = "Tomkins"},
                                                 new Contact() {firstName = "Henry", lastName = "Dorrell"},
                                                 new Contact() {firstName = "charles", lastName = "Florrie"},
                                                 new Contact() {firstName = "Henry", lastName = "Mylton"},
                                                 new Contact() {firstName = "Henry", lastName = "Payne"},
                                                 new Contact() {firstName = "Thomas", lastName = "Harris"},
                                                 new Contact() {firstName = "William", lastName = "Nicholes"},
                                                 new Contact() {firstName = "Thomas", lastName = "Phevens"},
                                                 new Contact() {firstName = "John", lastName = "Borden"},
                                                 new Contact() {firstName = "Thomas", lastName = "Scot"},
                                                 new Contact() {firstName = "William", lastName = "Willes"},
                                                 new Contact() {firstName = "John", lastName = "Brooke"},
                                                 new Contact() {firstName = "Cutbert", lastName = "White"},
                                                 new Contact() {firstName = "John", lastName = "Bright"},
                                                 new Contact() {firstName = "Clement", lastName = "Tayler"},
                                                 new Contact() {firstName = "William", lastName = "Sole"},
                                                 new Contact() {firstName = "John", lastName = "Cotsmur"},
                                                 new Contact() {firstName = "Humfrey", lastName = "Newton"},
                                                 new Contact() {firstName = "Thomas", lastName = "Colman"},
                                                 new Contact() {firstName = "Thomas", lastName = "Gramme"},
                                                 new Contact() {firstName = "Marke", lastName = "Bennet"},
                                                 new Contact() {firstName = "John", lastName = "Gibbes"},
                                                 new Contact() {firstName = "John", lastName = "Stilman"},
                                                 new Contact() {firstName = "Robert", lastName = "Wilkinson"},
                                                 new Contact() {firstName = "Peter", lastName = "Little"},
                                                 new Contact() {firstName = "John", lastName = "Wyles"},
                                                 new Contact() {firstName = "Brian", lastName = "Wyles"},
                                                 new Contact() {firstName = "George", lastName = "Martyn"},
                                                 new Contact() {firstName = "Hugh", lastName = "Pattenson"},
                                                 new Contact() {firstName = "Martyn", lastName = "Sutton"},
                                                 new Contact() {firstName = "John", lastName = "Farre"},
                                                 new Contact() {firstName = "John", lastName = "Bridger"},
                                                 new Contact() {firstName = "Griffen", lastName = "Jones"},
                                                 new Contact() {firstName = "Richard", lastName = "Shaberdge"},
                                                 new Contact() {firstName = "James", lastName = "Lasie"},
                                                 new Contact() {firstName = "John", lastName = "Cheven"},
                                                 new Contact() {firstName = "Thomas", lastName = "Hewet"},
                                             };

        [WebMethod()]
        [ScriptMethod(ResponseFormat = ResponseFormat.Json, UseHttpGet = true, XmlSerializeString = false)]
        public List<Contact> GetContacts(int start, int count)
        {
            if (start + count < contacts.Count)
            {
                return contacts.GetRange(start, count);
            }
            return new List<Contact>();
        }
    }

    [Serializable]
    public class Contact
    {
        public string firstName;
        public string lastName;
    }
}
